/**************************

This class is automatically generated by KFDataTool

***********************/
#include "AnyKFDTest.h"
#include "FVectorF.h"
#include "FVector_methods.h"
#include "KFTestObjectAF.h"
#include "KFTestObjectA_methods.h"
#include "KFTestObjectBF.h"
#include "KFTestObjectB_methods.h"

namespace KF
{
    kfAny AnyKFDTest::ReadFVector(KFByteArray& buffarr, kfAny obj)
    {
        FVector* cast_obj = static_cast<FVector*>(obj);
        return FVectorF::Read(buffarr, cast_obj);
    }
    void AnyKFDTest::WriteFVector(KFByteArray& buffarr, kfAny obj, KFDDirtys* dirtys)
    {
        FVector* cast_obj = static_cast<FVector*>(obj);
        FVectorF::Write(buffarr, cast_obj, dirtys);
    }
    void AnyKFDTest::DeleteFVector(kfAny obj)
    {
        FVector* cast_obj = static_cast<FVector*>(obj);
        kfDel(cast_obj);
    }
    bool AnyKFDTest::DiffFVector(kfAny old_obj, kfAny new_obj, KFDDirtys* dirtys)
    {
        FVector* cast_old_obj = static_cast<FVector*>(old_obj);
        FVector* cast_new_obj = static_cast<FVector*>(new_obj);
        return FVectorF::Diff(cast_old_obj, cast_new_obj, dirtys);
    }
    kfAny AnyKFDTest::CompactReadFVector(KFByteArray& buffarr, kfAny obj)
    {
        FVector* cast_obj = static_cast<FVector*>(obj);
        return FVectorF::CompactRead(buffarr, cast_obj);
    }
    void AnyKFDTest::CompactWriteFVector(KFByteArray& buffarr, kfAny obj)
    {
        FVector* cast_obj = static_cast<FVector*>(obj);
        FVectorF::CompactWrite(buffarr, cast_obj);
    }

    kfAny AnyKFDTest::ReadKFTestObjectA(KFByteArray& buffarr, kfAny obj)
    {
        KFTestObjectA* cast_obj = static_cast<KFTestObjectA*>(obj);
        return KFTestObjectAF::Read(buffarr, cast_obj);
    }
    void AnyKFDTest::WriteKFTestObjectA(KFByteArray& buffarr, kfAny obj, KFDDirtys* dirtys)
    {
        KFTestObjectA* cast_obj = static_cast<KFTestObjectA*>(obj);
        KFTestObjectAF::Write(buffarr, cast_obj, dirtys);
    }
    void AnyKFDTest::DeleteKFTestObjectA(kfAny obj)
    {
        KFTestObjectA* cast_obj = static_cast<KFTestObjectA*>(obj);
        kfDel(cast_obj);
    }
    bool AnyKFDTest::DiffKFTestObjectA(kfAny old_obj, kfAny new_obj, KFDDirtys* dirtys)
    {
        KFTestObjectA* cast_old_obj = static_cast<KFTestObjectA*>(old_obj);
        KFTestObjectA* cast_new_obj = static_cast<KFTestObjectA*>(new_obj);
        return KFTestObjectAF::Diff(cast_old_obj, cast_new_obj, dirtys);
    }
    kfAny AnyKFDTest::CompactReadKFTestObjectA(KFByteArray& buffarr, kfAny obj)
    {
        KFTestObjectA* cast_obj = static_cast<KFTestObjectA*>(obj);
        return KFTestObjectAF::CompactRead(buffarr, cast_obj);
    }
    void AnyKFDTest::CompactWriteKFTestObjectA(KFByteArray& buffarr, kfAny obj)
    {
        KFTestObjectA* cast_obj = static_cast<KFTestObjectA*>(obj);
        KFTestObjectAF::CompactWrite(buffarr, cast_obj);
    }

    kfAny AnyKFDTest::ReadKFTestObjectB(KFByteArray& buffarr, kfAny obj)
    {
        KFTestObjectB* cast_obj = static_cast<KFTestObjectB*>(obj);
        return KFTestObjectBF::Read(buffarr, cast_obj);
    }
    void AnyKFDTest::WriteKFTestObjectB(KFByteArray& buffarr, kfAny obj, KFDDirtys* dirtys)
    {
        KFTestObjectB* cast_obj = static_cast<KFTestObjectB*>(obj);
        KFTestObjectBF::Write(buffarr, cast_obj, dirtys);
    }
    void AnyKFDTest::DeleteKFTestObjectB(kfAny obj)
    {
        KFTestObjectB* cast_obj = static_cast<KFTestObjectB*>(obj);
        kfDel(cast_obj);
    }
    bool AnyKFDTest::DiffKFTestObjectB(kfAny old_obj, kfAny new_obj, KFDDirtys* dirtys)
    {
        KFTestObjectB* cast_old_obj = static_cast<KFTestObjectB*>(old_obj);
        KFTestObjectB* cast_new_obj = static_cast<KFTestObjectB*>(new_obj);
        return KFTestObjectBF::Diff(cast_old_obj, cast_new_obj, dirtys);
    }
    kfAny AnyKFDTest::CompactReadKFTestObjectB(KFByteArray& buffarr, kfAny obj)
    {
        KFTestObjectB* cast_obj = static_cast<KFTestObjectB*>(obj);
        return KFTestObjectBF::CompactRead(buffarr, cast_obj);
    }
    void AnyKFDTest::CompactWriteKFTestObjectB(KFByteArray& buffarr, kfAny obj)
    {
        KFTestObjectB* cast_obj = static_cast<KFTestObjectB*>(obj);
        KFTestObjectBF::CompactWrite(buffarr, cast_obj);
    }

    void AnyKFDTest::Regist()
    {
        if(IsRegisted)
            return;
        IsRegisted = true;

        REG_KFD_FORMAT_ANY("FVector",
            &AnyKFDTest::ReadFVector,
            &AnyKFDTest::WriteFVector,
            &AnyKFDTest::DeleteFVector,
            &AnyKFDTest::DiffFVector,
            &AnyKFDTest::CompactReadFVector,
            &AnyKFDTest::CompactWriteFVector,
            &FVector_methods::Regist);
        REG_KFD_REFLECTION("FVector", "", FVector);
        REG_KFD_FORMAT_ANY("KFTestObjectA",
            &AnyKFDTest::ReadKFTestObjectA,
            &AnyKFDTest::WriteKFTestObjectA,
            &AnyKFDTest::DeleteKFTestObjectA,
            &AnyKFDTest::DiffKFTestObjectA,
            &AnyKFDTest::CompactReadKFTestObjectA,
            &AnyKFDTest::CompactWriteKFTestObjectA,
            &KFTestObjectA_methods::Regist);
        REG_KFD_REFLECTION("KFTestObjectA", "KFGCObject", KFTestObjectA);
        REG_KFD_FORMAT_ANY("KFTestObjectB",
            &AnyKFDTest::ReadKFTestObjectB,
            &AnyKFDTest::WriteKFTestObjectB,
            &AnyKFDTest::DeleteKFTestObjectB,
            &AnyKFDTest::DiffKFTestObjectB,
            &AnyKFDTest::CompactReadKFTestObjectB,
            &AnyKFDTest::CompactWriteKFTestObjectB,
            &KFTestObjectB_methods::Regist);
        REG_KFD_REFLECTION("KFTestObjectB", "", KFTestObjectB);

    }


    bool AnyKFDTest::IsRegisted = false;
}
