/**************************

This class is automatically generated by KFDataTool

***********************/
#pragma once
#include "Format/KFDataFormat.h"

namespace KF
{
    class RA_API AnyKFDTest
    {
    public:
        static kfAny ReadFVector(KFByteArray& buffarr, kfAny obj = nullptr);
        static void WriteFVector(KFByteArray& buffarr, kfAny obj = nullptr, KFDDirtys* dirtys = nullptr);
        static void DeleteFVector(kfAny obj);
        static bool DiffFVector(kfAny old_obj, kfAny new_obj, KFDDirtys* dirtys = nullptr);
        static kfAny CompactReadFVector(KFByteArray& buffarr, kfAny obj = nullptr);
        static void CompactWriteFVector(KFByteArray& buffarr, kfAny obj = nullptr);
        
        static kfAny ReadKFTestObjectA(KFByteArray& buffarr, kfAny obj = nullptr);
        static void WriteKFTestObjectA(KFByteArray& buffarr, kfAny obj = nullptr, KFDDirtys* dirtys = nullptr);
        static void DeleteKFTestObjectA(kfAny obj);
        static bool DiffKFTestObjectA(kfAny old_obj, kfAny new_obj, KFDDirtys* dirtys = nullptr);
        static kfAny CompactReadKFTestObjectA(KFByteArray& buffarr, kfAny obj = nullptr);
        static void CompactWriteKFTestObjectA(KFByteArray& buffarr, kfAny obj = nullptr);
        
        static kfAny ReadKFTestObjectB(KFByteArray& buffarr, kfAny obj = nullptr);
        static void WriteKFTestObjectB(KFByteArray& buffarr, kfAny obj = nullptr, KFDDirtys* dirtys = nullptr);
        static void DeleteKFTestObjectB(kfAny obj);
        static bool DiffKFTestObjectB(kfAny old_obj, kfAny new_obj, KFDDirtys* dirtys = nullptr);
        static kfAny CompactReadKFTestObjectB(KFByteArray& buffarr, kfAny obj = nullptr);
        static void CompactWriteKFTestObjectB(KFByteArray& buffarr, kfAny obj = nullptr);
        
        static bool IsRegisted;
    	static void Regist();
    };
}
