/**************************

This class is automatically generated by KFDataTool

***********************/
#pragma once

#include "Format/KFDataFormat.h"
#include "KFDTestObject.h"

namespace KF {
    class RA_API FVectorF {
    public:
        static FVector* Read(KFByteArray& buffarr,FVector* obj = nullptr);
        static void Write(KFByteArray& buffarr,FVector* obj,KFDDirtys* dirtys = nullptr);
        static bool Diff(FVector* old_obj,FVector* new_obj,KFDDirtys* dirtys = nullptr);
        static FVector* CompactRead(KFByteArray& buffarr,FVector* obj = nullptr);
        static void CompactWrite(KFByteArray& buffarr,FVector* obj);

        static FVector* ReadFVector(KFByteArray& buffarr,FVector* obj = nullptr);
        static void WriteFVector(KFByteArray& buffarr,FVector* obj, KFDDirtys* dirtys = nullptr);
        static bool DiffFVector(FVector* old_obj,FVector* new_obj,KFDDirtys* dirtys = nullptr);
        static FVector* CompactReadFVector(KFByteArray& buffarr,FVector* obj = nullptr);
        static void CompactWriteFVector(KFByteArray& buffarr,FVector* obj);
    };

    class RA_API FVectorR {
    public:
        static KFDFieldResult GetField(kfAny obj, const kfname& fieldname, kfAny index);
        static bool SetField(kfAny obj, const kfname& fieldname, kfAny field, kfAny index);
        static kfAny New() { return kfNewObject(FVector); }
        static void Delete(kfAny ptr) { kfDeleteObject(static_cast<FVector*>(ptr)); }
        static kfAny Clone(kfAny obj);
        static bool Copy(kfAny src, kfAny dest);

        static FVector* CloneFVector(FVector* obj);
        static bool CopyFVector(FVector* src, FVector* dest);
    };
}
