/**************************

This class is automatically generated by KFDataTool

***********************/

#pragma once

#include "KFDTestObject.h"
#include "GC/KFGCSystem.h"
#include "Format/KFDataFormat.h"
#include "Pool/KFObjectPool.h"
#include "VM3/wrap/KF8FunctionLink.h"

namespace KF
{
    class RA_API KFTestObjectB_methods
    {
    public:
        static KFTestObjectB* New(KFTestObjectB* ptr = nullptr)
        {
            if (ptr)
                return KFSingleton<SimpleObjectPool<KFTestObjectB>>::Get().New(*ptr);
            else
                return KFSingleton<SimpleObjectPool<KFTestObjectB>>::Get().New();
        }

        static void Delete(KFTestObjectB* ptr)
        {
            KFSingleton<SimpleObjectPool<KFTestObjectB>>::Get().Delete(ptr);
        }

        static void Regist(kfMap<kfname, KFDMethodMeta>& Funcs)
        {
            Funcs.emplace("new",KFDMethodMeta([](kfAny target,kfAny retPtr,kfVector<kfAny>* argPtr){
				return_and_error_msg_if(!retPtr, "retPtr null!");
                auto& arg_list = *argPtr;
                KFTestObjectB* arg = arg_list.size() > 0 ?
                    *(KFTestObjectB**)arg_list[0] : nullptr;
                *((KFTestObjectB**)retPtr) = New(arg);
            }));

            Funcs.emplace("delete",KFDMethodMeta([](kfAny target,kfAny retPtr,kfVector<kfAny>* argPtr){
				return_and_error_msg_if(!target, "target null!");
                Delete((KFTestObjectB*)target);
            }));
        }
    };
}
