/**************************

This class is automatically generated by KFDataTool

***********************/
#pragma once

#include "Format/KFDataFormat.h"
#include "KFDTestObject.h"
#include "KFTestObjectAF.h"

namespace KF {
    class RA_API KFTestObjectBF {
    public:
        static KFTestObjectB* Read(KFByteArray& buffarr,KFTestObjectB* obj = nullptr);
        static void Write(KFByteArray& buffarr,KFTestObjectB* obj,KFDDirtys* dirtys = nullptr);
        static bool Diff(KFTestObjectB* old_obj,KFTestObjectB* new_obj,KFDDirtys* dirtys = nullptr);
        static KFTestObjectB* CompactRead(KFByteArray& buffarr,KFTestObjectB* obj = nullptr);
        static void CompactWrite(KFByteArray& buffarr,KFTestObjectB* obj);

        static KFTestObjectB* ReadKFTestObjectB(KFByteArray& buffarr,KFTestObjectB* obj = nullptr);
        static void WriteKFTestObjectB(KFByteArray& buffarr,KFTestObjectB* obj, KFDDirtys* dirtys = nullptr);
        static bool DiffKFTestObjectB(KFTestObjectB* old_obj,KFTestObjectB* new_obj,KFDDirtys* dirtys = nullptr);
        static KFTestObjectB* CompactReadKFTestObjectB(KFByteArray& buffarr,KFTestObjectB* obj = nullptr);
        static void CompactWriteKFTestObjectB(KFByteArray& buffarr,KFTestObjectB* obj);
    };

    class RA_API KFTestObjectBR {
    public:
        static KFDFieldResult GetField(kfAny obj, const kfname& fieldname, kfAny index);
        static bool SetField(kfAny obj, const kfname& fieldname, kfAny field, kfAny index);
        static kfAny New() { return kfNewObject(KFTestObjectB); }
        static void Delete(kfAny ptr) { kfDeleteObject(static_cast<KFTestObjectB*>(ptr)); }
        static kfAny Clone(kfAny obj);
        static bool Copy(kfAny src, kfAny dest);

        static KFTestObjectB* CloneKFTestObjectB(KFTestObjectB* obj);
        static bool CopyKFTestObjectB(KFTestObjectB* src, KFTestObjectB* dest);
    };
}
