/**************************

This class is automatically generated by KFDataTool

***********************/
#pragma once

#include "Format/KFDataFormat.h"
#include "KFDTestObject.h"
#include "FVectorF.h"

namespace KF {
    class RA_API KFTestObjectAF {
    public:
        static KFTestObjectA* Read(KFByteArray& buffarr,KFTestObjectA* obj = nullptr);
        static void Write(KFByteArray& buffarr,KFTestObjectA* obj,KFDDirtys* dirtys = nullptr);
        static bool Diff(KFTestObjectA* old_obj,KFTestObjectA* new_obj,KFDDirtys* dirtys = nullptr);
        static KFTestObjectA* CompactRead(KFByteArray& buffarr,KFTestObjectA* obj = nullptr);
        static void CompactWrite(KFByteArray& buffarr,KFTestObjectA* obj);

        static KFTestObjectA* ReadKFTestObjectA(KFByteArray& buffarr,KFTestObjectA* obj = nullptr);
        static void WriteKFTestObjectA(KFByteArray& buffarr,KFTestObjectA* obj, KFDDirtys* dirtys = nullptr);
        static bool DiffKFTestObjectA(KFTestObjectA* old_obj,KFTestObjectA* new_obj,KFDDirtys* dirtys = nullptr);
        static KFTestObjectA* CompactReadKFTestObjectA(KFByteArray& buffarr,KFTestObjectA* obj = nullptr);
        static void CompactWriteKFTestObjectA(KFByteArray& buffarr,KFTestObjectA* obj);
    };

    class RA_API KFTestObjectAR {
    public:
        static KFDFieldResult GetField(kfAny obj, const kfname& fieldname, kfAny index);
        static bool SetField(kfAny obj, const kfname& fieldname, kfAny field, kfAny index);
        static kfAny New() { return kfNewObject(KFTestObjectA); }
        static void Delete(kfAny ptr) { kfDeleteObject(static_cast<KFTestObjectA*>(ptr)); }
        static kfAny Clone(kfAny obj);
        static bool Copy(kfAny src, kfAny dest);

        static KFTestObjectA* CloneKFTestObjectA(KFTestObjectA* obj);
        static bool CopyKFTestObjectA(KFTestObjectA* src, KFTestObjectA* dest);
    };
}
