/**************************

This class is automatically generated by KFDataTool

***********************/

#pragma once

#include "KFDTestObject.h"
#include "GC/KFGCSystem.h"
#include "Format/KFDataFormat.h"
#include "Pool/KFObjectPool.h"
#include "VM3/wrap/KF8FunctionLink.h"

namespace KF
{
    class RA_API KFTestObjectA_methods
    {
    public:
        static KFTestObjectA* New(KFTestObjectA* ptr = nullptr)
        {
            return kfNewObject(KFTestObjectA);
        }

        static void Delete(KFTestObjectA* ptr)
        {
            kfDeleteObject(ptr);
        }

        static void Regist(kfMap<kfname, KFDMethodMeta>& Funcs)
        {
            Funcs.emplace("new",KFDMethodMeta([](kfAny target,kfAny retPtr,kfVector<kfAny>* argPtr){
				return_and_error_msg_if(!retPtr, "retPtr null!");
                auto& arg_list = *argPtr;
                KFTestObjectA* arg = arg_list.size() > 0 ?
                    *(KFTestObjectA**)arg_list[0] : nullptr;
                *((KFTestObjectA**)retPtr) = New(arg);
            }));

            Funcs.emplace("delete",KFDMethodMeta([](kfAny target,kfAny retPtr,kfVector<kfAny>* argPtr){
				return_and_error_msg_if(!target, "target null!");
                Delete((KFTestObjectA*)target);
            }));

            Funcs.emplace("AddToValue1",KFDMethodMeta([](kfAny target,kfAny retPtr,kfVector<kfAny>* argPtr){
                return_and_error_msg_if(!target, "target null!");
                KFTestObjectA* instance = (KFTestObjectA*) target;
        	    auto& arg_list = *argPtr;
        	    auto arg_size = arg_list.size();
				return_and_error_msg_if(arg_size < 2, "arg list size invalid, %llu/2!", arg_size);
                if(retPtr)
                {
                    *((float*)retPtr) = instance->AddToValue1(
                        *((float*)arg_list[0]),
                        *((float*)arg_list[1])
                    );
                }
                else
                {
            	    instance->AddToValue1(
                        *((float*)arg_list[0]),
                        *((float*)arg_list[1])
                    );
                }
            }, KFDMethodMeta::TypeMeta((KFDataType)7,"")));

            Funcs.emplace("AutoParseMethod",KFDMethodMeta([](kfAny target,kfAny retPtr,kfVector<kfAny>* argPtr){
                return_and_error_msg_if(!target, "target null!");
                KFTestObjectA* instance = (KFTestObjectA*) target;
        	    auto& arg_list = *argPtr;
        	    auto arg_size = arg_list.size();
				return_and_error_msg_if(arg_size < 2, "arg list size invalid, %llu/2!", arg_size);
                if(retPtr)
                {
                    *((float*)retPtr) = instance->AutoParseMethod(
                        *((float*)arg_list[0]),
                        *((float*)arg_list[1])
                    );
                }
                else
                {
            	    instance->AutoParseMethod(
                        *((float*)arg_list[0]),
                        *((float*)arg_list[1])
                    );
                }
            }, KFDMethodMeta::TypeMeta((KFDataType)7,"")));
        }
    };
}
