/**************************

This class is automatically generated by KFDataTool

***********************/


#pragma once

#include "KFData/Format/KFDataFormat.h"
{% for index, includestr in data.includes %}
#include "{{includestr}}"
{%end%}
{% if data.extend %}
#include "{{data.extend}}F.h"
{%end%}

namespace {{NS}}
{
    class KFENGINERT_API {{data.class}}F
    {
    public:
        static {{data.class}}* Read(KFByteArray& buffarr,{{data.class}}* obj = nullptr);
        static void Write(KFByteArray& buffarr,{{data.class}}* obj);
        static {{data.class}}* Read{{data.class}}(KFByteArray& buffarr,{{data.class}}* obj = nullptr);
        static void Write{{data.class}}(KFByteArray& buffarr,{{data.class}}* obj);
    };
}