/**************************

This class is automatically generated by KFDataTool

***********************/


#pragma once


#include "KFData/Format/KFDataFormat.h"
#include "{{CLASS}}F.h"

namespace {{NS}}
{
    class KFENGINERT_API {{CLASS}}TypeDef
    {
{% if DEF_ENUM%}
    public:
     enum {{CLASS}}TypeEnum
     {
        UNDEFINED = 0,
    {% if USECLSID %}
        {% for index, kfd in data.kfddatas %}
        KF_ST_ENUM_{{kfd.class}} = {{kfd.clsid}},
        {%end%}
    {%else%}
        {% for index, kfd in data.kfddatas %}
        KF_ST_ENUM_{{kfd.class}} = {{kfd.typeid}},
        {%end%}
    {%end%}
    };
{%end%}

    public:
        static {{CLASS}}* Create(uint32 keytype);
        static {{CLASS}}* Read(KFByteArray& buffarr,{{CLASS}}* obj = nullptr);
        static void Write(KFByteArray& buffarr,{{CLASS}}* obj);
        static kfMap<kfstr,int32> KeyTypes;
    };
}