/**************************

This class is automatically generated by KFDataTool

***********************/


#pragma once

#include "KFData/Format/KFDataFormat.h"
#include "KFDTest.h"

namespace KF
{
    class KFENGINERT_API BaseAF
    {
    public:
        static BaseA* Read(KFByteArray& buffarr,BaseA* obj = nullptr);
        static void Write(KFByteArray& buffarr,BaseA* obj);
        static BaseA* ReadBaseA(KFByteArray& buffarr,BaseA* obj = nullptr);
        static void WriteBaseA(KFByteArray& buffarr,BaseA* obj);
    };
}
