/**************************

This class is automatically generated by KFDataTool

***********************/


#pragma once

#include "KFData/Format/KFDataFormat.h"
#include "KFDTest.h"
#include "BaseAF.h"

namespace KF
{
    class KFENGINERT_API ClsBF
    {
    public:
        static ClsB* Read(KFByteArray& buffarr,ClsB* obj = nullptr);
        static void Write(KFByteArray& buffarr,ClsB* obj);
        static ClsB* ReadClsB(KFByteArray& buffarr,ClsB* obj = nullptr);
        static void WriteClsB(KFByteArray& buffarr,ClsB* obj);
    };
}
