/**************************

This class is automatically generated by KFDataTool

***********************/


#pragma once

#include "KFData/Format/KFDataFormat.h"
#include "KFScript/Data/KFFrameData.h"
#include "KFScriptDataF.h"

namespace KF
{
    class KFENGINERT_API KFFrameDataF
    {
    public:
        static KFFrameData* Read(KFByteArray& buffarr,KFFrameData* obj = nullptr);
        static void Write(KFByteArray& buffarr,KFFrameData* obj);
        static KFFrameData* ReadKFFrameData(KFByteArray& buffarr,KFFrameData* obj = nullptr);
        static void WriteKFFrameData(KFByteArray& buffarr,KFFrameData* obj);
    };
}
