/**************************

This class is automatically generated by KFDataTool

***********************/


#pragma once


#include "KFData/Format/KFDataFormat.h"
#include "KFScriptDataF.h"

namespace KF
{
    class KFENGINERT_API KFScriptDataTypeDef
    {

    public:
        static KFScriptData* Create(uint32 keytype);
        static KFScriptData* Read(KFByteArray& buffarr,KFScriptData* obj = nullptr);
        static void Write(KFByteArray& buffarr,KFScriptData* obj);
        static kfMap<kfstr,int32> KeyTypes;
    };
}
