/**************************

This class is automatically generated by KFDataTool

***********************/


#pragma once

#include "KFData/Format/KFDataFormat.h"
#include "KFScript/Data/KFScriptData.h"

namespace KF
{
    class KFENGINERT_API KFScriptDataF
    {
    public:
        static KFScriptData* Read(KFByteArray& buffarr,KFScriptData* obj = nullptr);
        static void Write(KFByteArray& buffarr,KFScriptData* obj);
        static KFScriptData* ReadKFScriptData(KFByteArray& buffarr,KFScriptData* obj = nullptr);
        static void WriteKFScriptData(KFByteArray& buffarr,KFScriptData* obj);
    };
}
