/**************************

This class is automatically generated by KFDataTool

***********************/

\#pragma once

\#include "KF8TypeDef.h"
#if $extendcls != ""
\#include "v${extendcls}.h"
#end if
#for $funcInclude in $funcsincludes
#if $funcInclude != $extendName
\#include "v${funcInclude}.h"
#end if
#end for

#set global $containerTypes = ["arr", "mixarr", "map", "mixmap", "omap", "mixomap"]
#*

*#
#def ContainerTypeName($param)
#if $param.type in ["arr", "mixarr"]
vkfVector<$RetTypeName($param.value_type_prop)>#slurp
#else if $param.type in ["map", "mixmap"]
vkfMap<$RetTypeName($param.key_type_prop), $RetTypeName($param.value_type_prop)>#slurp
#else if $param.type in ["omap", "mixomap"]
vkfOMap<$RetTypeName($param.key_type_prop), $RetTypeName($param.value_type_prop)>#slurp
#end if
#end def
#*

*#
#def TypeName($param)
#if $param.type == "mixobject" and $param.otype != "char"
const v${param.otype}&#slurp
#else if $param.type == "null"
void#slurp
#else if $param.type == "object"
const v${param.otype}&#slurp
#else if $param.type == "kfstr" or $param.type == "kfname"
const v${param.type}&#slurp
#else if $param.type in $containerTypes
const $ContainerTypeName($param)&#slurp
#else if $param.isKFRef == True
const vkfRef<v${param.otype}>&#slurp
#else
$param.rawType#slurp
#end if
#end def
#*

*#
#def DefalutValue($param)
#if $param.defaultval != None and ($param.defaultval.find('(') == -1 or $param.defaultval.find('()') != -1)
#if $param.type == "mixobject" and $param.otype != "char"
#if $param.defaultval == "null" or $param.defaultval == "nullptr"
 = v${param.otype}()#slurp
#end if
#else if $param.type == "object"
 = MakeInstance(${param.otype})#slurp
#else if $param.type == "kfstr" or $param.type == "kfname"
 = $param.defaultval#slurp
#else if $param.type in $containerTypes
 = MakeInstance($ContainerTypeName($param))#slurp
#else if $param.isKFRef == True
 = vkfRef<v${param.otype}>($param.defaultval)#slurp
#else
 = $param.defaultval#slurp
#end if
#end if
#end def
#*

*#
#def RetTypeName($param)
#if $param.isKFRef == True
vkfRef<v${param.otype}>#slurp
#else if ($param.type == "mixobject" and $param.otype != "char") or $param.type == "object"
v${param.otype}#slurp
#else if $param.type == "kfstr" or $param.type == "kfname"
v${param.type}#slurp
#else if $param.type == "null"
void#slurp
#else if $param.type in $containerTypes
$ContainerTypeName($param)#slurp
#else
$param.rawType#slurp
#end if
#end def
#*

*#
#if $root_base_class == "KFGCObject"
    #set $isgcobject = True
#else if $root_base_class == "UObject"
    #set $isuobject = True
#end if
#*

*#
#if $extendcls != ""
    #set $extendName = 'v' + $extendcls
#else if $isgcobject == True
    #set $extendName = "vGCObject"
#else if $isuobject == True
    #set $extendName = "vUObject"
#else
    #set $extendName = "vAutoObject"
#end if
#*

*#
#if $isgcobject == True
    #set $ctorParamName = "vGCObject"
#else if $isuobject == True
    #set $ctorParamName = "vUObject"
#else
    #set $ctorParamName = "vAutoObject"
#end if
#*

*#
class v${data.class} : public $extendName
{
public:
#if $isgcobject == True
    v${data.class}(ObjectPtr ptr = 0, int32 cls = -1, bool noRef = false): ${extendName}(ptr, cls == -1 ? getClsID() : cls, noRef) {}
    explicit v${data.class}(const $ctorParamName& obj, int32 cls = -1, bool noRef = false)
        : ${extendName}(obj.RawObjectPtr(), cls != -1 ? cls : obj.ClassName() > 0 ? obj.ClassName() : getClsID(), noRef) {}
#else if $isuobject == True
    v${data.class}(ObjectPtr ptr = 0, int32 cls = -1, bool strongRef = false): ${extendName}(ptr, cls == -1 ? getClsID() : cls, strongRef) {}
    explicit v${data.class}(const $ctorParamName& obj, int32 cls = -1, bool strongRef = false)
        : ${extendName}(obj.RawObjectPtr(), cls != -1 ? cls : obj.ClassName() > 0 ? obj.ClassName() : getClsID(), strongRef) {}
#else
    v${data.class}(ObjectPtr ptr = 0, int32 cls = -1, bool autoDelete = false)
        : ${extendName}(ptr, cls == -1 ? getClsID() : cls, autoDelete) {}
    explicit v${data.class}(const $ctorParamName& obj, int32 cls = -1, bool autoDelete = false)
        : ${extendName}(obj.RawObjectPtr(), cls != -1 ? cls : obj.ClassName() > 0 ? obj.ClassName() : getClsID(), autoDelete) {}
#end if

#if "funcs" in $data
    #for $func in $data.funcs
        #if $func.gen != False
            #if "alias" in $func:
                #set $funcName = $func.alias
            #else
                #set $funcName = $func.name
            #end if
        	#if "isStatic" not in $func
                #set $staticDesc = ''
            #else
                #set $staticDesc = 'static '
            #end if
#if $len($func.params) > 0
    ${staticDesc}$RetTypeName($func.retparam) ${funcName}(
#else
    ${staticDesc}$RetTypeName($func.retparam) ${funcName}()
#end if
    #for $i in range($len($func.params))
        #if $i == $len($func.params) - 1
            #set $comma=""
        #else
            #set $comma=","
        #end if
        $TypeName($func.params[$i]) ${func.params[$i].name}$DefalutValue($func.params[$i])$comma
    #end for
#if $len($func.params) > 0
        )
#end if
    {
#if $func.retparam.type != "null"
    #if $func.retparam.type == "mixobject" or $func.retparam.type == "object" or $func.retparam.type == "kfstr"
        ObjectPtr ret = 0;
    #else if $func.retparam.type in $containerTypes
        ObjectPtr ret = 0;
    #else if $func.retparam.type == "kfname"
        int32 ret = 0;
    #else
        $func.retparam.rawType ret = 0;
    #end if
#end if
    #if "isStatic" not in $func
        Call("$funcName"
    #else
        _AnyCallT(getClsID(), "$funcName", 0
    #end if
    #if $func.retparam.type != "null"
            , &ret
    #else
            , 0
    #end if
    #for $i in range($len($func.params))
        #if $func.params[$i].type == "mixobject" and $func.params[$i].otype != "char"
            , ${func.params[$i].name}.RawObjectPtr()
        #else if $func.params[$i].type == "object"
            , ${func.params[$i].name}.RawObjectPtr()
        #else if $func.params[$i].type == "kfstr" or $func.params[$i].type == "kfname"
            , ${func.params[$i].name}.RawObjectPtr()
        #else if $func.params[$i].type in $containerTypes
            , ${func.params[$i].name}.RawObjectPtr()
        #else
            , ${func.params[$i].name}
        #end if
    #end for
        );
#if $func.retparam.type != "null"
    #if $func.retparam.isRef == True
        #set $autoDelete = "false"
    #else
        #set $autoDelete = "true"
    #end if
    #if $func.retparam.type == "mixobject" and $func.retparam.otype == "char"
        if (ret)
        {
            return ($func.retparam.rawType)_TS(ret, 0);
        }
        return 0;
    #else if $func.retparam.type == "object"
        return $RetTypeName($func.retparam)(ret, -1, $autoDelete);
    #else if $func.retparam.type == "kfstr"
        return vkfstr(ret, $autoDelete);
    #else if $func.retparam.type == "kfname"
        return vkfname(ret);
    #else if $func.retparam.type in $containerTypes
        return $RetTypeName($func.retparam)(ret, $autoDelete);
    #else
        return ret;
    #end if
#end if
    }

        #end if
    #end for
#end if
public:
	static int32 getClsID()
	{
		static int32 id = 0;
		if (id == 0)
		{
			id = _N(clsname);
		}
		return id;
	}
	static constexpr char const * clsname = "${data.class}";
};
