/**************************

This class is automatically generated by KFDataTool

***********************/
\#pragma once
\#include "Format/KFDataFormat.h"
#if $export_api==""
	#set $export_api="KFENGINERT_API"
#end if

namespace ${NS}
{
    class $export_api Any${CLASS}
    {
    public:
#for $data in $datas
        static kfAny Read${data.class}(KFByteArray& buffarr, kfAny obj = nullptr);
        static void Write${data.class}(KFByteArray& buffarr, kfAny obj = nullptr, KFDDirtys* dirtys = nullptr);
        static void Delete${data.class}(kfAny obj);
        static bool Diff${data.class}(kfAny old_obj, kfAny new_obj, KFDDirtys* dirtys = nullptr);
        static kfAny CompactRead${data.class}(KFByteArray& buffarr, kfAny obj = nullptr);
        static void CompactWrite${data.class}(KFByteArray& buffarr, kfAny obj = nullptr);
        
 #end for
        static bool IsRegisted;
    	static void Regist();
    };
}
