/**************************

This class is automatically generated by KFDataTool

***********************/
\#include "${CLASS}_methods.h"

namespace ${NS}
{
    void ${CLASS}_methods::Regist()
    {

    }
}
