/**************************

This class is automatically generated by KFDataTool

***********************/
\#include "Any${CLASS}.h"
#for $includestr in $includes 
\#include "${includestr}"
#end for

namespace ${NS}
{
#for $data in $datas
#if "nof" not in $data or $data.nof != 1
    kfAny Any${CLASS}::Read${data.class}(KFByteArray& buffarr, kfAny obj)
    {
        ${data.class}* cast_obj = static_cast<${data.class}*>(obj);
        return ${data.class}F::Read(buffarr, cast_obj);
    }
    void Any${CLASS}::Write${data.class}(KFByteArray& buffarr, kfAny obj, KFDDirtys* dirtys)
    {
        ${data.class}* cast_obj = static_cast<${data.class}*>(obj);
        ${data.class}F::Write(buffarr, cast_obj, dirtys);
    }
    void Any${CLASS}::Delete${data.class}(kfAny obj)
    {
        ${data.class}* cast_obj = static_cast<${data.class}*>(obj);
        kfDel(cast_obj);
    }
    bool Any${CLASS}::Diff${data.class}(kfAny old_obj, kfAny new_obj, KFDDirtys* dirtys)
    {
        ${data.class}* cast_old_obj = static_cast<${data.class}*>(old_obj);
        ${data.class}* cast_new_obj = static_cast<${data.class}*>(new_obj);
        return ${data.class}F::Diff(cast_old_obj, cast_new_obj, dirtys);
    }
    kfAny Any${CLASS}::CompactRead${data.class}(KFByteArray& buffarr, kfAny obj)
    {
        ${data.class}* cast_obj = static_cast<${data.class}*>(obj);
        return ${data.class}F::CompactRead(buffarr, cast_obj);
    }
    void Any${CLASS}::CompactWrite${data.class}(KFByteArray& buffarr, kfAny obj)
    {
        ${data.class}* cast_obj = static_cast<${data.class}*>(obj);
        ${data.class}F::CompactWrite(buffarr, cast_obj);
    }

#end if
#end for
    void Any${CLASS}::Regist()
    {
        if(IsRegisted)
            return;
        IsRegisted = true;

      #for $data in $datas
      #if "nof" not in $data or $data.nof != 1
        REG_KFD_FORMAT_ANY("${data.class}",
            &Any${CLASS}::Read${data.class},
            &Any${CLASS}::Write${data.class},
            &Any${CLASS}::Delete${data.class},
            &Any${CLASS}::Diff${data.class},
            &Any${CLASS}::CompactRead${data.class},
            &Any${CLASS}::CompactWrite${data.class},
        #if $data.method == 0
            null);
        #else
            &${data.class}_methods::Regist);
        #end if
        REG_KFD_REFLECTION("${data.class}", "${data.__src_extend__}", ${data.class});
      #else if $data.method == 1
        REG_KFD_FORMAT_ANY("${data.class}",
            null, null, null, null, null, null,
            &${data.class}_methods::Regist);
      #end if
      #end for

      #if $containers != None
      #for $container in $containers
        REG_KFD_FORMAT_ANY("$container",
            null, null, null, null, null, null,
            &${container}_methods::Regist);
      #end for
      #end if
    }


    bool Any${CLASS}::IsRegisted = false;
}
