/**************************

This class is automatically generated by KFDataTool

***********************/
\#include "${CLASS}.h"
#for $group in $groups 
\#include "Any${group.group}.h"
#end for

namespace ${NS}
{
    void ${CLASS}::RegistAll()
    {
      #for $group_name in $distinct_group_names
        Any${group_name}::Regist();
      #end for
    }
}
